### ISSUE TITLE
Update nokogiri library because of vulnerability

### ISSUE THREAD

**Issue by aibou** [codenize-tools/piculet#37]
GitHub shows these warnings.

![image](https://user-images.githubusercontent.com/311408/38791527-4131d73e-4183-11e8-9a42-3a85613cdd55.png)

I propose we should update this gem.

**Comment by k1LoW** [comment]
refs https://github.com/codenize-tools/piculet/pull/29

**Comment by aibou** [comment]
Are you still using ruby 1.9 or 2.0? Why?
These versions has been already no longer supported.

**Comment by k1LoW** [comment]
I think that it is necessary to decide carefully the support version. Because piculet is a tool for infrastructure.

For example, latest CentOS use ruby 2.0.0 😕 

```sh
[vagrant@localhost ~]$ cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
[vagrant@localhost ~]$ sudo yum list | grep ruby
Failed to set locale, defaulting to C
graphviz-ruby.x86_64                        2.30.1-19.el7              base
kross-ruby.x86_64                           4.10.5-8.el7               base
libselinux-ruby.x86_64                      2.5-11.el7                 base
marisa-ruby.x86_64                          0.2.4-4.el7                base
openwsman-ruby.x86_64                       2.3.6-14.el7               base
plasma-scriptengine-ruby.x86_64             4.11.19-8.el7              base
rrdtool-ruby.x86_64                         1.4.8-9.el7                base
ruby.x86_64                                 2.0.0.648-33.el7_4         updates
subversion-ruby.x86_64                      1.7.14-11.el7_4            updates
```

But 'vulnerability' is a very important reason.

**Comment by limitusus** [comment]
IMHO we should update nokogiri version.

We should keep using the latest Ruby and libraries versions independently of runtime or libraries versions provided by package manager.
Especially Ruby 2.0.x security fix support had ended Feb 2016 (2 years ago!), so no user should use this version of Ruby, except with like RHEL support, but should use the latest Ruby runtime with rbenv or so.
I don't think we should expose users to vulnerability just due to Ruby in CentOS's repository. We should rather give users the push to use the latest Ruby and libraries, independent of package managers.

**Comment by winebarrel** [comment]
I think it would be better to upgrade version nokogiri.
Since piculet is a client tool, I think that it is not necessary to become nervous about the version of Ruby.

Can someone review https://github.com/codenize-tools/piculet/pull/38 ? 🙏

**Comment by winebarrel** [comment]
fixed.
0.3.0.beta2 has been released.
